/**
  ******************************************************************************
  * @file   config.h
  * @author Jonathan Taylor
  * @date   12/6/22
  * @brief  DESCRIPTION
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 Jonathan Taylor.
  * All rights reserved.
  *
  ******************************************************************************
  */

#ifndef MODBUS_CLIENT_CONFIG_H
#define MODBUS_CLIENT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define N_SUB_CHANNELS 6

#define MB_NAMESPACE "modbus"

#define MB_COIL_NAMESPACE MB_NAMESPACE ".coil"
#define MB_DI_NAMESPACE MB_NAMESPACE ".discrete_inputs"
#define MB_HR_NAMESPACE MB_NAMESPACE ".holding_registers"
#define MB_IR_NAMESPACE MB_NAMESPACE ".input_registers"

#define MB_READ_NAMESPACE ".read"
#define MB_WRITE_NAMESPACE ".write"

#define MB_REQUEST_NAMESPACE ".req"
#define MB_RESPONSE_NAMESPACE ".res"

#define MB_READ_COIL_REQ_CHANNEL MB_COIL_NAMESPACE MB_READ_NAMESPACE MB_REQUEST_NAMESPACE
#define MB_READ_COIL_RES_CHANNEL MB_COIL_NAMESPACE MB_READ_NAMESPACE MB_RESPONSE_NAMESPACE

#define MB_READ_DI_REQ_CHANNEL MB_DI_NAMESPACE MB_READ_NAMESPACE MB_REQUEST_NAMESPACE
#define MB_READ_DI_RES_CHANNEL MB_DI_NAMESPACE MB_READ_NAMESPACE MB_RESPONSE_NAMESPACE

#define MB_READ_HR_REQ_CHANNEL MB_HR_NAMESPACE MB_READ_NAMESPACE MB_REQUEST_NAMESPACE
#define MB_READ_HR_RES_CHANNEL MB_HR_NAMESPACE MB_READ_NAMESPACE MB_RESPONSE_NAMESPACE

#define MB_READ_IR_REQ_CHANNEL MB_IR_NAMESPACE MB_READ_NAMESPACE MB_REQUEST_NAMESPACE
#define MB_READ_IR_RES_CHANNEL MB_IR_NAMESPACE MB_READ_NAMESPACE MB_RESPONSE_NAMESPACE

#define MB_WRITE_COIL_REQ_CHANNEL MB_COIL_NAMESPACE MB_WRITE_NAMESPACE MB_REQUEST_NAMESPACE
#define MB_WRITE_COIL_RES_CHANNEL MB_COIL_NAMESPACE MB_WRITE_NAMESPACE MB_RESPONSE_NAMESPACE

#define MB_WRITE_HR_REQ_CHANNEL MB_HR_NAMESPACE MB_WRITE_NAMESPACE MB_REQUEST_NAMESPACE
#define MB_WRITE_HR_RES_CHANNEL MB_HR_NAMESPACE MB_WRITE_NAMESPACE MB_RESPONSE_NAMESPACE

#ifdef __cplusplus
}
#endif

#endif //MODBUS_CLIENT_CONFIG_H
